# Generated by Django 5.1.3 on 2025-03-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillSets',
            new_name='SkillSet',
        ),
    ]
