# Generated by Django 5.1.3 on 2025-03-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_details', '0002_rename_skillsets_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
