# Generated by Django 5.1.3 on 2025-03-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_details', '0003_alter_article_image_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
