# Generated by Django 5.1.3 on 2025-03-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_details', '0005_alter_article_image_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
