# Generated by Django 5.1.3 on 2025-03-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_details', '0006_alter_workingexperience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingexperience',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
