# Generated by Django 5.1.3 on 2025-03-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_details', '0007_workingexperience_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingexperience',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
