# Generated by Django 5.1.3 on 2025-03-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_details', '0008_alter_workingexperience_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='year_experience',
            field=models.IntegerField(default=0),
        ),
    ]
