# Generated by Django 5.1.3 on 2025-03-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_details', '0010_remove_portfolio_image_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='summary',
            field=models.CharField(blank=True, null=True),
        ),
    ]
