# Generated by Django 5.1.3 on 2025-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_details', '0011_portfolio_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
